### ISSUE TITLE
Not working with version 1.1

### ISSUE THREAD

**Issue by eV1lMoF0** [sparr/factorio-mod-combinator-text#1]
Needs Updating to 1.1,

Changed the info.json file to factorio_version: 1.1 then went into a game and tried to use it and it came up with this

The mod Combinator Graph Generator (1.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event combinatorgraph::on_player_selected_area (ID 50)
combinatorgraph/control.lua:5: attempt to index local 'condition' (a nil value)
stack traceback:
combinatorgraph/control.lua:5: in function 'ConditionLabel'
combinatorgraph/control.lua:120: in function '?'
combinatorgraph/control.lua:325: in function 'EntityLabel'
combinatorgraph/control.lua:364: in function 'GraphCombinators'
combinatorgraph/control.lua:395: in function <combinatorgraph/control.lua:393>

Dont know enough programing to fix it

**Comment by sparr** [comment]
I believe this was fixed with mod version 1.1.0
